CREATE TABLE IF NOT EXISTS encuestas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  edad VARCHAR(20),
  genero VARCHAR(30),
  depto VARCHAR(40),
  provincia_origen VARCHAR(80),
  situacion_educativa VARCHAR(60),
  carrera VARCHAR(100),
  estrato VARCHAR(30),
  estatus_laboral VARCHAR(40),
  medio_info VARCHAR(30),
  intencion_1v VARCHAR(20),
  firmeza TINYINT,
  ideologia VARCHAR(25),
  participacion_actividades VARCHAR(25),
  voto_ultimas BOOLEAN,
  economia TINYINT,
  empleo TINYINT,
  educacion_importancia TINYINT,
  calidad_universitaria TINYINT,
  acceso_becas TINYINT,
  interes_politica TINYINT,
  salud_publica TINYINT,
  seguridad_ciudadana TINYINT,
  cambio_climatico TINYINT,
  temas_genero TINYINT,
  indigenas TINYINT,
  modelo_desarrollo TINYINT,
  acceso_internet TINYINT,
  digitalizacion_servicios TINYINT,
  participacion_local TINYINT,
  transparencia_contratos TINYINT,
  rendicion_cuentas TINYINT,
  exp_gestion_A TINYINT,
  honestidad_A TINYINT,
  union_A TINYINT,
  jovenes_A TINYINT,
  liderazgo_A TINYINT,
  propuestas_A TINYINT,
  exp_gestion_B TINYINT,
  honestidad_B TINYINT,
  union_B TINYINT,
  jovenes_B TINYINT,
  liderazgo_B TINYINT,
  propuestas_B TINYINT,
  freq_actividad_politica VARCHAR(50),
  ha_participado_marcha VARCHAR(5),
  miembro_partido VARCHAR(25),
  interes_politica_nacional VARCHAR(25),
  situacion_actual_pais VARCHAR(25),
  esperanza_economia VARCHAR(25),
  optimismo_futuro VARCHAR(25),
  confianza_voto VARCHAR(25),
  seguroEleccion TINYINT,
  influencia_medios TINYINT  -- Asegúrate de incluir esta línea
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
