-- 15+ variables, lista para MySQL
CREATE TABLE IF NOT EXISTS encuestas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  edad VARCHAR(20),
  genero VARCHAR(30),
  depto VARCHAR(40),
  provincia_origen VARCHAR(80),
  situacion_educativa VARCHAR(60),
  carrera VARCHAR(100),
  estrato VARCHAR(30),
  estatus_laboral VARCHAR(40),
  medio_info VARCHAR(30),
  intencion_1v VARCHAR(20),
  firmeza TINYINT,
  ideologia VARCHAR(25),
  participacion_politica VARCHAR(20),
  voto_ultimas BOOLEAN,
  interes_politica TINYINT,
  economia TINYINT,
  empleo TINYINT,
  educacion_importancia TINYINT,
  corrupcion_justicia TINYINT,
  salud_publica TINYINT,
  seguridad TINYINT,
  medio_ambiente TINYINT,
  derechos_sociales TINYINT,
  modelo_desarrollo TINYINT,
  exp_gestion_A TINYINT,
  honestidad_A TINYINT,
  union_A TINYINT,
  jovenes_A TINYINT,
  liderazgo_A TINYINT,
  propuestas_A TINYINT,
  exp_gestion_B TINYINT,
  honestidad_B TINYINT,
  union_B TINYINT,
  jovenes_B TINYINT,
  liderazgo_B TINYINT,
  propuestas_B TINYINT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
